import type { Schedule } from './types';

// Data transcribed from the provided image with route details
export const SCHEDULE_DATA: Schedule = {
  weekday: [
    {
      name: '从兰台出发',
      loopingServices: [
        { startTime: '07:20', endTime: '09:40', routeDetail: '兰台 → 北门转盘 → 纪忠楼 (循环发车)' },
      ],
      departures: [
        // Morning
        { time: '07:30', routeDetail: '兰台 → 北门 → 转盘' },
        { time: '07:30', routeDetail: '兰台 → 北门 → 转盘' },
        { time: '07:40', routeDetail: '兰台 → 北门 → 转盘' },
        { time: '09:40', routeDetail: '兰台 → 北门 → 转盘' },
        { time: '09:40', routeDetail: '兰台 → 北门 → 转盘' },
        // Mid-day & Evening
        { time: '10:00', routeDetail: '兰台 → 北门转盘' },
        { time: '10:20', routeDetail: '兰台 → 北门转盘 → 文学院 → 纪忠楼' },
        { time: '10:30', routeDetail: '兰台 → 北门转盘' },
        { time: '11:00', routeDetail: '兰台 → 北门转盘' },
        { time: '11:10', routeDetail: '兰台 → 北门转盘 → 文学院 → 纪忠楼' },
        { time: '11:20', routeDetail: '兰台 → 北门转盘' },
        { time: '11:40', routeDetail: '兰台 → 北门转盘' },
        { time: '11:55', routeDetail: '兰台 → 北门转盘' },
        { time: '12:10', routeDetail: '兰台 → 北门转盘' },
        { time: '12:20', routeDetail: '兰台 → 北门转盘' },
        { time: '12:40', routeDetail: '兰台 → 北门转盘' },
        { time: '12:50', routeDetail: '兰台 → 北门转盘' },
        { time: '13:05', routeDetail: '兰台 → 北门转盘' },
        { time: '13:20', routeDetail: '兰台 → 北门转盘' },
        { time: '13:40', routeDetail: '兰台 → 北门转盘 → 文学院 → 纪忠楼' },
        { time: '14:00', routeDetail: '兰台 → 北门转盘' },
        { time: '14:20', routeDetail: '兰台 → 北门转盘' },
        { time: '14:30', routeDetail: '兰台 → 北门转盘 → 文学院 → 纪忠楼' },
        { time: '14:40', routeDetail: '兰台 → 北门转盘' },
        { time: '15:00', routeDetail: '兰台 → 北门转盘' },
        { time: '15:20', routeDetail: '兰台 → 北门转盘' },
        { time: '15:30', routeDetail: '兰台 → 北门转盘 → 文学院 → 纪忠楼' },
        { time: '15:40', routeDetail: '兰台 → 北门转盘' },
        { time: '16:00', routeDetail: '兰台 → 北门转盘' },
        { time: '16:20', routeDetail: '兰台 → 北门转盘 → 文学院 → 纪忠楼' },
        { time: '16:30', routeDetail: '兰台 → 北门转盘' },
        { time: '16:50', routeDetail: '兰台 → 北门转盘' },
        { time: '17:10', routeDetail: '兰台 → 北门转盘' },
        { time: '17:10', routeDetail: '兰台 → 北门转盘 → 文学院 → 纪忠楼' },
        { time: '17:20', routeDetail: '兰台 → 北门转盘' },
        { time: '17:40', routeDetail: '兰台 → 北门转盘' },
        { time: '17:50', routeDetail: '兰台 → 北门转盘' },
        { time: '18:00', routeDetail: '兰台 → 北门转盘' },
        { time: '18:20', routeDetail: '兰台 → 北门转盘' },
        { time: '18:30', routeDetail: '兰台 → 北门转盘' },
        { time: '18:40', routeDetail: '兰台 → 北门转盘' },
        { time: '18:40', routeDetail: '兰台 → 北门转盘 → 文学院 → 纪忠楼' },
        { time: '18:50', routeDetail: '兰台 → 北门转盘' },
        { time: '19:10', routeDetail: '兰台 → 北门转盘' },
        { time: '19:30', routeDetail: '兰台 → 北门转盘 → 文学院 → 纪忠楼' },
        { time: '19:45', routeDetail: '兰台 → 北门转盘' },
        { time: '20:05', routeDetail: '兰台 → 北门转盘' },
        { time: '20:25', routeDetail: '兰台 → 北门转盘' },
        { time: '20:25', routeDetail: '兰台 → 北门转盘 → 文学院 → 纪忠楼' },
        { time: '20:45', routeDetail: '兰台 → 北门转盘' },
        { time: '21:05', routeDetail: '兰台 → 北门转盘' },
        { time: '21:25', routeDetail: '兰台 → 北门转盘' },
        { time: '21:45', routeDetail: '兰台 → 北门转盘' },
        { time: '22:05', routeDetail: '兰台 → 北门转盘' },
        { time: '22:15', routeDetail: '兰台 → 北门转盘' },
        { time: '22:25', routeDetail: '兰台 → 北门转盘' },
      ].sort((a, b) => a.time.localeCompare(b.time)),
    },
    {
      name: '前往兰台',
      loopingServices: [
        { startTime: '07:30', endTime: '09:50', routeDetail: '纪忠楼 → 北门转盘 → 兰台 (循环发车)' },
      ],
      departures: [
        { time: '10:10', routeDetail: '北门转盘 → 兰台' },
        { time: '10:40', routeDetail: '北门转盘 → 兰台' },
        { time: '10:50', routeDetail: '纪忠楼 → 文学院 → 北门转盘 → 兰台' },
        { time: '11:10', routeDetail: '北门转盘 → 兰台' },
        { time: '11:30', routeDetail: '北门转盘 → 兰台' },
        { time: '11:40', routeDetail: '纪忠楼 → 文学院 → 北门转盘 → 兰台' },
        { time: '11:50', routeDetail: '北门转盘 → 兰台' },
        { time: '12:00', routeDetail: '北门转盘 → 兰台' },
        { time: '12:20', routeDetail: '北门转盘 → 兰台' },
        { time: '12:30', routeDetail: '北门转盘 → 兰台' },
        { time: '12:30', routeDetail: '纪忠楼 → 文学院 → 北门转盘 → 兰台' },
        { time: '12:40', routeDetail: '北门转盘 → 兰台' },
        { time: '13:00', routeDetail: '北门转盘 → 兰台' },
        { time: '13:10', routeDetail: '北门转盘 → 兰台' },
        { time: '13:30', routeDetail: '北门转盘 → 兰台' },
        { time: '14:10', routeDetail: '北门转盘 → 兰台' },
        { time: '14:30', routeDetail: '北门转盘 → 兰台' },
        { time: '14:50', routeDetail: '北门转盘 → 兰台' },
        { time: '15:00', routeDetail: '纪忠楼 → 文学院 → 北门转盘 → 兰台' },
        { time: '15:10', routeDetail: '北门转盘 → 兰台' },
        { time: '15:30', routeDetail: '北门转盘 → 兰台' },
        { time: '15:50', routeDetail: '北门转盘 → 兰台' },
        { time: '15:50', routeDetail: '纪忠楼 → 文学院 → 北门转盘 → 兰台' },
        { time: '16:10', routeDetail: '北门转盘 → 兰台' },
        { time: '16:40', routeDetail: '北门转盘 → 兰台' },
        { time: '16:50', routeDetail: '纪忠楼 → 文学院 → 北门转盘 → 兰台' },
        { time: '17:00', routeDetail: '北门转盘 → 兰台' },
        { time: '17:10', routeDetail: '北门转盘 → 兰台' },
        { time: '17:30', routeDetail: '北门转盘 → 兰台' },
        { time: '17:40', routeDetail: '北门转盘 → 兰台' },
        { time: '17:40', routeDetail: '纪忠楼 → 文学院 → 北门转盘 → 兰台' },
        { time: '17:50', routeDetail: '北门转盘 → 兰台' },
        { time: '18:00', routeDetail: '北门转盘 → 兰台' },
        { time: '18:10', routeDetail: '北门转盘 → 兰台' },
        { time: '18:30', routeDetail: '北门转盘 → 兰台' },
        { time: '18:30', routeDetail: '纪忠楼 → 文学院 → 北门转盘 → 兰台' },
        { time: '18:40', routeDetail: '北门转盘 → 兰台' },
        { time: '18:50', routeDetail: '北门转盘 → 兰台' },
        { time: '19:00', routeDetail: '北门转盘 → 兰台' },
        { time: '19:20', routeDetail: '北门转盘 → 兰台' },
        { time: '19:40', routeDetail: '北门转盘 → 兰台' },
        { time: '19:55', routeDetail: '纪忠楼 → 文学院 → 北门转盘 → 兰台' },
        { time: '20:00', routeDetail: '北门转盘 → 兰台' },
        { time: '20:20', routeDetail: '北门转盘 → 兰台' },
        { time: '20:40', routeDetail: '北门转盘 → 兰台' },
        { time: '20:50', routeDetail: '纪忠楼 → 文学院 → 北门转盘 → 兰台' },
        { time: '21:00', routeDetail: '北门转盘 → 兰台' },
        { time: '21:20', routeDetail: '北门转盘 → 兰台' },
        { time: '21:40', routeDetail: '北门转盘 → 兰台' },
        { time: '21:40', routeDetail: '纪忠楼 → 文学院 → 北门转盘 → 兰台' },
        { time: '22:00', routeDetail: '北门转盘 → 兰台' },
        { time: '22:10', routeDetail: '北门转盘 → 兰台' },
        { time: '22:20', routeDetail: '北门转盘 → 兰台' },
        { time: '22:30', routeDetail: '北门转盘 → 兰台' },
      ].sort((a, b) => a.time.localeCompare(b.time)),
    },
  ],
  holiday: [
    {
      name: '从兰台出发',
      departures: [
        { time: '07:20', routeDetail: '兰台 → 北门圆盘' },
        { time: '07:40', routeDetail: '兰台 → 北门圆盘 → 纪忠楼' },
        { time: '08:00', routeDetail: '兰台 → 北门圆盘' },
        { time: '08:20', routeDetail: '兰台 → 北门圆盘' },
        { time: '08:40', routeDetail: '兰台 → 北门圆盘' },
        { time: '09:00', routeDetail: '兰台 → 北门圆盘' },
        { time: '09:20', routeDetail: '兰台 → 北门圆盘' },
        { time: '09:40', routeDetail: '兰台 → 北门圆盘' },
        { time: '10:00', routeDetail: '兰台 → 北门圆盘' },
        { time: '10:30', routeDetail: '兰台 → 北门圆盘' },
        { time: '10:50', routeDetail: '兰台 → 北门圆盘' },
        { time: '11:10', routeDetail: '兰台 → 北门圆盘' },
        { time: '11:30', routeDetail: '兰台 → 北门圆盘' },
        { time: '11:50', routeDetail: '兰台 → 北门圆盘' },
        { time: '12:10', routeDetail: '兰台 → 北门圆盘' },
        { time: '12:30', routeDetail: '兰台 → 北门圆盘' },
        { time: '12:50', routeDetail: '兰台 → 北门圆盘' },
        { time: '13:00', routeDetail: '兰台 → 北门圆盘' },
        { time: '13:20', routeDetail: '兰台 → 北门圆盘' },
        { time: '13:40', routeDetail: '兰台 → 北门圆盘' },
        { time: '14:00', routeDetail: '兰台 → 北门圆盘' },
        { time: '14:20', routeDetail: '兰台 → 北门圆盘' },
        { time: '14:40', routeDetail: '兰台 → 北门圆盘' },
        { time: '15:00', routeDetail: '兰台 → 北门圆盘' },
        { time: '15:20', routeDetail: '兰台 → 北门圆盘' },
        { time: '15:40', routeDetail: '兰台 → 北门圆盘' },
        { time: '16:00', routeDetail: '兰台 → 北门圆盘' },
        { time: '16:20', routeDetail: '兰台 → 北门圆盘' },
        { time: '16:40', routeDetail: '兰台 → 北门圆盘' },
        { time: '17:00', routeDetail: '兰台 → 北门圆盘' },
        { time: '17:20', routeDetail: '兰台 → 北门圆盘' },
        { time: '17:40', routeDetail: '兰台 → 北门圆盘' },
        { time: '18:00', routeDetail: '兰台 → 北门圆盘' },
        { time: '18:20', routeDetail: '兰台 → 北门圆盘' },
        { time: '18:40', routeDetail: '兰台 → 北门圆盘' },
        { time: '19:00', routeDetail: '兰台 → 北门圆盘' },
        { time: '19:20', routeDetail: '兰台 → 北门圆盘' },
        { time: '19:35', routeDetail: '兰台 → 北门圆盘' },
        { time: '19:55', routeDetail: '兰台 → 北门圆盘' },
        { time: '20:15', routeDetail: '兰台 → 北门圆盘' },
        { time: '20:35', routeDetail: '兰台 → 北门圆盘' },
        { time: '20:55', routeDetail: '兰台 → 北门圆盘' },
        { time: '21:15', routeDetail: '兰台 → 北门圆盘' },
        { time: '21:35', routeDetail: '兰台 → 北门圆盘' },
        { time: '21:55', routeDetail: '兰台 → 北门圆盘' },
        { time: '22:15', routeDetail: '兰台 → 北门圆盘' },
        { time: '22:25', routeDetail: '兰台 → 北门圆盘' },
      ],
    },
    {
      name: '前往兰台',
      departures: [
        '07:30', '07:50', '08:10', '08:30', '08:50', '09:10', '09:30', '09:50', '10:10',
        '10:40', '11:00', '11:20', '11:40', '12:00', '12:20', '12:40', '12:55', '13:10',
        '13:30', '13:50', '14:10', '14:30', '14:50', '15:10', '15:30', '15:50', '16:10',
        '16:30', '16:50', '17:10', '17:30', '17:50', '18:10', '18:30', '18:50', '19:10',
        '19:30', '19:50', '20:10', '20:30', '20:50', '21:10', '21:30', '21:50', '22:10',
        '22:20', '22:30'
      ].map(time => ({ time, routeDetail: '北门圆盘 → 兰台' })),
    },
  ],
};
